# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/metamagic',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/metamagic',
                'lib_path': 'metamagic'},
  'syms': {'metamagic.core': {'metamagic.core.foo': ('core.html#foo', 'metamagic/core.py')}}}
